### ISSUE TITLE
Removing locations can break solver

### ISSUE THREAD

**Issue by yurloc** [kiegroup/optaweb-vehicle-routing#15]
Load European cities, remove them all one by one and repeat.
```
17:29:21.426 [lTaskExecutor-1] ERROR             o.o.t.o.TspMapController - Solver error: 
java.lang.IllegalStateException: Visit Optional.empty has been removed previously.
	at org.optaweb.tsp.optawebtspplanner.TspPlannerComponent.addToRoute(TspPlannerComponent.java:67)
	at org.optaweb.tsp.optawebtspplanner.TspPlannerComponent.extractRoute(TspPlannerComponent.java:93)
	at org.optaweb.tsp.optawebtspplanner.TspPlannerComponent.sendRoute(TspPlannerComponent.java:99)
	at org.optaweb.tsp.optawebtspplanner.TspPlannerComponent.bestSolutionChanged(TspPlannerComponent.java:128)
	at org.optaplanner.core.impl.solver.event.SolverEventSupport.fireBestSolutionChanged(SolverEventSupport.java:48)
	at org.optaplanner.core.impl.solver.recaller.BestSolutionRecaller.updateBestSolution(BestSolutionRecaller.java:136)
	at org.optaplanner.core.impl.solver.recaller.BestSolutionRecaller.processWorkingSolutionDuringStep(BestSolutionRecaller.java:96)
	at org.optaplanner.core.impl.localsearch.DefaultLocalSearchPhase.doStep(DefaultLocalSearchPhase.java:104)
	at org.optaplanner.core.impl.localsearch.DefaultLocalSearchPhase.solve(DefaultLocalSearchPhase.java:92)
	at org.optaplanner.core.impl.solver.AbstractSolver.runPhases(AbstractSolver.java:87)
	at org.optaplanner.core.impl.solver.DefaultSolver.solve(DefaultSolver.java:191)
	at org.optaweb.tsp.optawebtspplanner.TspPlannerComponent.lambda$addPlace$2(TspPlannerComponent.java:155)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by yurloc** [comment]
No longer reproducible.
