### ISSUE TITLE
WebSocket session disconnected when adding a visit

### ISSUE THREAD

**Issue by yurloc** [kiegroup/optaweb-vehicle-routing#94]
Happens often with some regions. For example Spain and Brazil. Might be caused by long distance matrix calculation time but it **also hapens during solving** - needs investigation. Hopefully it can be solved by increasing heartbeat interval. Or removing some stupid mistake like doing too much on the thread that processes the WebSocket message.

**Comment by yurloc** [comment]
It's actually caused by exceeding WebSocket session [send buffer size limit](https://github.com/spring-projects/spring-framework/blob/v5.1.6.RELEASE/spring-websocket/src/main/java/org/springframework/web/socket/config/annotation/WebSocketTransportRegistration.java#L112) on the back end.

<details>
<summary>Interesting log excerpt:</summary>
<pre>
17:07:03.754 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 32h 20m 54s
17:07:03.918 [boundChannel-12] TRACE .ConcurrentWebSocketSessionDecorator - Another send already in progress: session id 'lxh3ozwj':, "in-progress" send time 501 (ms), buffer size 1681979 bytes
17:07:03.919 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 32h 12m 44s
17:07:04.040 [boundChannel-14] TRACE .ConcurrentWebSocketSessionDecorator - Another send already in progress: session id 'lxh3ozwj':, "in-progress" send time 623 (ms), buffer size 3368011 bytes
17:07:04.040 [boundChannel-14] DEBUG .s.w.s.m.SubProtocolWebSocketHandler - Terminating 'WebSocketServerSockJsSession[id=lxh3ozwj]'
org.springframework.web.socket.handler.SessionLimitExceededException: The send buffer size 3368011 bytes for session 'lxh3ozwj' exceeded the allowed limit 2097152
	at org.springframework.web.socket.handler.ConcurrentWebSocketSessionDecorator.limitExceeded(ConcurrentWebSocketSessionDecorator.java:188)
	at org.springframework.web.socket.handler.ConcurrentWebSocketSessionDecorator.checkSessionLimits(ConcurrentWebSocketSessionDecorator.java:177)
	at org.springframework.web.socket.handler.ConcurrentWebSocketSessionDecorator.sendMessage(ConcurrentWebSocketSessionDecorator.java:132)
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.sendToClient(StompSubProtocolHandler.java:453)
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.handleMessageToClient(StompSubProtocolHandler.java:440)
	at org.springframework.web.socket.messaging.SubProtocolWebSocketHandler.handleMessage(SubProtocolWebSocketHandler.java:343)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17:07:04.040 [boundChannel-14] DEBUG .s.w.s.m.SubProtocolWebSocketHandler - Clearing session lxh3ozwj
17:07:04.041 [boundChannel-15] DEBUG .s.w.s.m.SubProtocolWebSocketHandler - No session for GenericMessage [payload=byte[0], headers={simpMessageType=DISCONNECT_ACK, simpDisconnectMessage=GenericMessage [payload=byte[0], headers={simpMessageType=DISCONNECT, stompCommand=DISCONNECT, simpSessionAttributes={}, simpSessionId=lxh3ozwj}], simpSessionId=lxh3ozwj}]
17:07:04.041 [boundChannel-14] DEBUG s.s.t.s.WebSocketServerSockJsSession - Closing SockJS session lxh3ozwj with CloseStatus[code=4500, reason=null]
17:07:04.041 [boundChannel-14] DEBUG     o.s.w.s.a.NativeWebSocketSession - Closing StandardWebSocketSession[id=f, uri=/vrp-websocket/376/lxh3ozwj/websocket]
17:07:04.123 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 30h 59m 6s
17:07:04.446 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 30h 59m 0s
17:07:04.619 [boundChannel-14] DEBUG s.h.LoggingWebSocketHandlerDecorator - WebSocketServerSockJsSession[id=lxh3ozwj] closed with CloseStatus[code=4500, reason=null]
17:07:04.619 [boundChannel-14] DEBUG .s.w.s.m.SubProtocolWebSocketHandler - Clearing session lxh3ozwj
17:07:04.619 [tboundChannel-1] DEBUG .s.w.s.m.SubProtocolWebSocketHandler - No session for GenericMessage [payload=byte[0], headers={simpMessageType=DISCONNECT_ACK, simpDisconnectMessage=GenericMessage [payload=byte[0], headers={simpMessageType=DISCONNECT, stompCommand=DISCONNECT, simpSessionAttributes={org.springframework.messaging.simp.SimpAttributes.COMPLETED=true}, simpSessionId=lxh3ozwj}], simpSessionId=lxh3ozwj}]
17:07:04.625 [boundChannel-13] DEBUG s.s.t.s.WebSocketServerSockJsSession - Terminating connection after failure to send message to client
java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:424)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialString(WsRemoteEndpointImplBase.java:223)
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:49)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:216)
	at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:100)
	at org.springframework.web.socket.sockjs.transport.session.WebSocketServerSockJsSession.writeFrameInternal(WebSocketServerSockJsSession.java:224)
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:324)
	at org.springframework.web.socket.sockjs.transport.session.WebSocketServerSockJsSession.sendMessageInternal(WebSocketServerSockJsSession.java:213)
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.sendMessage(AbstractSockJsSession.java:168)
	at org.springframework.web.socket.handler.ConcurrentWebSocketSessionDecorator.tryFlushMessageBuffer(ConcurrentWebSocketSessionDecorator.java:153)
	at org.springframework.web.socket.handler.ConcurrentWebSocketSessionDecorator.sendMessage(ConcurrentWebSocketSessionDecorator.java:126)
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.sendToClient(StompSubProtocolHandler.java:453)
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.handleMessageToClient(StompSubProtocolHandler.java:440)
	at org.springframework.web.socket.messaging.SubProtocolWebSocketHandler.handleMessage(SubProtocolWebSocketHandler.java:343)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
17:07:04.626 [boundChannel-13] DEBUG    o.s.w.s.m.StompSubProtocolHandler - Failed to send WebSocket message to client in session lxh3ozwj
org.springframework.web.socket.sockjs.SockJsTransportFailureException: Failed to write SockJsFrame content='a["MESSAGE\ndestination:/topic/route\ncontent-type:application/json;charset=UTF-...(truncated)'; nested exception is java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:341)
	at org.springframework.web.socket.sockjs.transport.session.WebSocketServerSockJsSession.sendMessageInternal(WebSocketServerSockJsSession.java:213)
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.sendMessage(AbstractSockJsSession.java:168)
	at org.springframework.web.socket.handler.ConcurrentWebSocketSessionDecorator.tryFlushMessageBuffer(ConcurrentWebSocketSessionDecorator.java:153)
	at org.springframework.web.socket.handler.ConcurrentWebSocketSessionDecorator.sendMessage(ConcurrentWebSocketSessionDecorator.java:126)
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.sendToClient(StompSubProtocolHandler.java:453)
	at org.springframework.web.socket.messaging.StompSubProtocolHandler.handleMessageToClient(StompSubProtocolHandler.java:440)
	at org.springframework.web.socket.messaging.SubProtocolWebSocketHandler.handleMessage(SubProtocolWebSocketHandler.java:343)
	at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:138)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Message will not be sent because the WebSocket session has been closed
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.writeMessagePart(WsRemoteEndpointImplBase.java:424)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:309)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendMessageBlock(WsRemoteEndpointImplBase.java:250)
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendPartialString(WsRemoteEndpointImplBase.java:223)
	at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendText(WsRemoteEndpointBasic.java:49)
	at org.springframework.web.socket.adapter.standard.StandardWebSocketSession.sendTextMessage(StandardWebSocketSession.java:216)
	at org.springframework.web.socket.adapter.AbstractWebSocketSession.sendMessage(AbstractWebSocketSession.java:100)
	at org.springframework.web.socket.sockjs.transport.session.WebSocketServerSockJsSession.writeFrameInternal(WebSocketServerSockJsSession.java:224)
	at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:324)
	... 11 common frames omitted
17:07:04.736 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 30h 51m 40s
17:07:04.841 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 30h 48m 35s
17:07:04.984 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 30h 31m 19s
17:07:05.116 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 30h 31m 8s
17:07:05.477 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 30h 16m 43s
17:07:05.864 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 30h 12m 35s
17:07:06.080 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 30h 10m 14s
17:07:06.195 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 30h 2m 37s
17:07:06.318 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 29h 38m 7s
17:07:06.478 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 29h 11m 23s
17:07:06.620 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 28h 49m 8s
17:07:07.285 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 28h 20m 23s
17:07:07.476 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 28h 4m 33s
17:07:07.883 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 27h 54m 50s
17:07:09.415 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 27h 43m 35s
17:07:09.811 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 27h 22m 45s
17:07:10.055 [MessageBroker-1] DEBUG   o.s.w.s.s.t.h.DefaultSockJsService - Closed 1 sessions: [lxh3ozwj]
17:07:10.315 [cTaskExecutor-2] INFO    o.o.v.p.planner.RouteOptimizerImpl - New solution with 1 depots, 6 vehicles, 26 customers, distance: 27h 21m 42s
17:07:10.749 [cTaskExecutor-2] INFO     o.o.c.i.l.DefaultLocalSearchPhase - Local Search phase (1) ended: time spent (10000), best score (0hard/-98502499soft), score calculation speed (8924/sec), step total (4263).
17:07:13.223 [nio-8080-exec-8] DEBUG  o.s.w.s.s.s.WebSocketHandlerMapping - Matching patterns for request [/vrp-websocket/info] are [/vrp-websocket/**]
17:07:13.223 [nio-8080-exec-8] DEBUG  o.s.w.s.s.s.WebSocketHandlerMapping - URI Template variables for request [/vrp-websocket/info] are {}
17:07:13.223 [nio-8080-exec-8] DEBUG  o.s.w.s.s.s.WebSocketHandlerMapping - Mapping [/vrp-websocket/info] to HandlerExecutionChain with handler [org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler@6dbb47a7] and 1 interceptor
17:07:13.224 [nio-8080-exec-8] DEBUG   o.s.w.s.s.t.h.DefaultSockJsService - Processing transport request: GET http://localhost:8080/vrp-websocket/info?t=1556896033218
17:07:13.237 [nio-8080-exec-9] DEBUG  o.s.w.s.s.s.WebSocketHandlerMapping - Matching patterns for request [/vrp-websocket/934/vsuy4bdy/websocket] are [/vrp-websocket/**]
17:07:13.237 [nio-8080-exec-9] DEBUG  o.s.w.s.s.s.WebSocketHandlerMapping - URI Template variables for request [/vrp-websocket/934/vsuy4bdy/websocket] are {}
17:07:13.237 [nio-8080-exec-9] DEBUG  o.s.w.s.s.s.WebSocketHandlerMapping - Mapping [/vrp-websocket/934/vsuy4bdy/websocket] to HandlerExecutionChain with handler [org.springframework.web.socket.sockjs.support.SockJsHttpRequestHandler@6dbb47a7] and 1 interceptor
17:07:13.237 [nio-8080-exec-9] DEBUG   o.s.w.s.s.t.h.DefaultSockJsService - Processing transport request: GET http://localhost:8080/vrp-websocket/934/vsuy4bdy/websocket
17:07:13.237 [nio-8080-exec-9] TRACE  o.s.w.s.s.s.DefaultHandshakeHandler - Processing request http://localhost:8080/vrp-websocket/934/vsuy4bdy/websocket with headers={host=[localhost:8080], connection=[Upgrade], pragma=[no-cache], cache-control=[no-cache], upgrade=[websocket], origin=[http://localhost:3000], sec-websocket-version=[13], user-agent=[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.108 Safari/537.36], accept-encoding=[gzip, deflate, br], accept-language=[en-US,en;q=0.9], sec-websocket-key=[kl0SrLw7m3m9xee2RnHdag==], sec-websocket-extensions=[permessage-deflate; client_max_window_bits]}
17:07:13.237 [nio-8080-exec-9] TRACE  o.s.w.s.s.s.DefaultHandshakeHandler - Upgrading to WebSocket, subProtocol=null, extensions=[]
17:07:13.239 [nio-8080-exec-9] DEBUG s.h.LoggingWebSocketHandlerDecorator - New WebSocketServerSockJsSession[id=vsuy4bdy]
17:07:13.239 [nio-8080-exec-9] TRACE     o.s.w.s.a.NativeWebSocketSession - Sending TextMessage payload=[o], byteCount=1, last=true], StandardWebSocketSession[id=10, uri=/vrp-websocket/934/vsuy4bdy/websocket]
17:07:13.239 [nio-8080-exec-9] TRACE s.s.t.s.WebSocketServerSockJsSession - Scheduled heartbeat in session vsuy4bdy
17:07:13.242 [io-8080-exec-10] TRACE s.h.LoggingWebSocketHandlerDecorator - Handling TextMessage payload=[CONNECT
ac..], byteCount=52, last=true] in WebSocketServerSockJsSession[id=vsuy4bdy]
17:07:13.242 [io-8080-exec-10] TRACE    o.s.w.s.m.StompSubProtocolHandler - From client: CONNECT session=vsuy4bdy
17:07:13.243 [boundChannel-16] TRACE s.s.t.s.WebSocketServerSockJsSession - Cancelling heartbeat in session vsuy4bdy
17:07:13.243 [boundChannel-16] TRACE s.s.t.s.WebSocketServerSockJsSession - Preparing to write SockJsFrame content='a["CONNECTED\nversion:1.2\nheart-beat:0,0\n\n\u0000"]'
17:07:13.243 [boundChannel-16] TRACE s.s.t.s.WebSocketServerSockJsSession - Writing SockJsFrame content='a["CONNECTED\nversion:1.2\nheart-beat:0,0\n\n\u0000"]'
17:07:13.243 [boundChannel-16] TRACE     o.s.w.s.a.NativeWebSocketSession - Sending TextMessage payload=[a["CONNECT..], byteCount=53, last=true], StandardWebSocketSession[id=10, uri=/vrp-websocket/934/vsuy4bdy/websocket]
</pre>
</details>

I'm gonna increase the buffer size limit temporarily and later:
1. Review portable classes to make sure no unnecessary bytes are being sent.
2. Put in place a message throttling mechanism to limit the frequency of updates (best thing we can do is to bulk-add locations to route optimizer instead of adding them one by one when loading a demo or restarting the app).

**Comment by yurloc** [comment]
Explanation of Spain, Brazil etc. could be that when visits are far from each other, it requires much more latlng points to describe the route and that increases the message size.

**Comment by yurloc** [comment]
The ideal, scalable solution for limiting the routing plan message size is to adjust the number of points describing paths based on the zoom level. For example in Norway, Lindensen lighthouse - Cape North and back (one direction: 2.527 km, 36h) now takes 3.6 MB to describe (
`content-type:application/json;charset=UTF-8`, `content-length:1888308`). For each path, we need up to number of pixels on a display diagonal (2880 on 4K UHD, each point is now described as `{"lat":57.98259,"lng":7.04823},` (31 chars -> content length 89k -> 180 KB, which is 95% reduction but we could go lower as we probably need much less points).
